<?php

/**
 * This is the model base class for the table "{{image}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Image".
 *
 * Columns in table "{{image}}" available as properties of the model,
 * followed by relations of table "{{image}}" available as properties of the model.
 *
 * @property integer $id
 * @property string $title
 * @property integer $holder_id
 *
 * @property ImagesHolder $holder
 */
abstract class BaseImage extends GxActiveRecord
{

    public static function model($className = __CLASS__)
    {
        return parent::model($className);
    }

    public function tableName()
    {
        return '{{image}}';
    }

    public static function label($n = 1)
    {
        return Yii::t('app', 'Image|Images', $n);
    }

    public static function representingColumn()
    {
        return 'title';
    }

    public function rules()
    {
        return array(
            array('title', 'required'),
            array('holder_id', 'numerical', 'integerOnly' => true),
            array('title', 'length', 'max' => 255),
            array('holder_id', 'default', 'setOnEmpty' => true, 'value' => null),
            array('id, title, holder_id', 'safe', 'on' => 'search'),
        );
    }

    public function relations()
    {
        return array(
            'holder' => array(self::BELONGS_TO, 'ImagesHolder', 'holder_id'),
        );
    }

    public function pivotModels()
    {
        return array(
        );
    }

    public function attributeLabels()
    {
        return array(
            'id' => Yii::t('app', 'ID'),
            'title' => Yii::t('app', 'Title'),
            'holder_id' => null,
            'holder' => null,
        );
    }

    public function search()
    {
        $criteria = new CDbCriteria;

        $criteria->compare('id', $this->id);
        $criteria->compare('title', $this->title, true);
        $criteria->compare('holder_id', $this->holder_id);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }
}