<?php

/**
 * This is the model base class for the table "{{images_holder}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ImagesHolder".
 *
 * Columns in table "{{images_holder}}" available as properties of the model,
 * followed by relations of table "{{images_holder}}" available as properties of the model.
 *
 * @property integer $id
 * @property string $type
 *
 * @property HeldImage[] $images
 */
abstract class BaseImagesHolder extends GxActiveRecord
{

    public static function model($className = __CLASS__)
    {
        return parent::model($className);
    }

    public function tableName()
    {
        return '{{images_holder}}';
    }

    public static function label($n = 1)
    {
        return Yii::t('app', 'ImagesHolder|ImagesHolders', $n);
    }

    public static function representingColumn()
    {
        return 'type';
    }

    public function rules()
    {
        return array(
            array('type', 'required'),
            array('type', 'length', 'max' => 16),
            array('id, type', 'safe', 'on' => 'search'),
        );
    }

    public function relations()
    {
        return array(
            'images' => array(self::HAS_MANY, 'HeldImage', 'holder_id'),
        );
    }

    public function pivotModels()
    {
        return array(
        );
    }

    public function attributeLabels()
    {
        return array(
            'id' => Yii::t('app', 'ID'),
            'type' => Yii::t('app', 'Type'),
            'images' => null,
        );
    }

    public function search()
    {
        $criteria = new CDbCriteria;

        $criteria->compare('id', $this->id);
        $criteria->compare('type', $this->type, true);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }
}